
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: consignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consignment
  template:
    metadata:
      labels:
        app: consignment
    spec:
        containers:
        - name: consignment-service
          image: eu.gcr.io/fidelis-microservice/consignment-service:latest
          imagePullPolicy: Always
          command: [
            "./consignment-service",
            "--selector=static",
            "--server_address=:8080"
          ]
          env:
          - name: DB_HOST
            value: "mongo:27017"
          - name: UPDATED_AT
            value: "Fri 27 Apr 2018 15:13:13 WAT"
          ports:
          - containerPort: 8080
            name: cons-port
