apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
        containers:
        - name: user-service
          image: eu.gcr.io/fidelis-microservice/user-service:latest
          imagePullPolicy: Always
          command: [
            "./user-service",
            "--selector=static",
            "--server_address=:8080"
          ]
          env:
          - name: DB_HOST
            value: "microservice-db:5432"
          - name: DB_NAME
            value: "user_service"
          - name: DB_PASS
            value: "userServicePassword"
          - name: JSONSecret
            value: "randomJSONSECRETKEY018918918080222@@@yayah"
          - name: DB_USER
            value: "user_service"
          - name: UPDATED_AT
            value: "Thu  3 May 2018 12:18:08 WAT"
          ports:
          - containerPort: 8080
            name: user-port
